name: Publish to PyPI (Trusted Publisher)

on:
  push:
    tags:
      - "v*.*.*"   # e.g., v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # required for OIDC
      contents: read
    # This must match the "Environment name" you’ll enter on PyPI (recommended: pypi)
    environment: pypi

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: python -m pip install -U pip build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true   # allows re-tag without failing if files exist
